if: tag IS present
dist: xenial
language: python
python:
- '3.7'
install:
- pip install wheel
script: echo "No build-time tests to run."
deploy:
  provider: pypi
  user: adamrehn
  distributions: bdist_wheel
  on:
    tags: true
  password:
    secure: W/4CR3tSa6v4toIIaSwGU+6VS5QjpjdD37RyB4y/MtLnz2+VP+Xve28wiEFNaui2Udyx9ro35kB1N9uJ+46+4tioKxOazWZultEPEDcujd832ijKeBY6OExPFdqYcT/Gy35ECxOivEwFVZ9iJ1qZmQaAU6c9pbANIjj/H7lqk/mBN0EyUrVTfynxBRWfMYxxFQhiEL8zO/siSRJHlZzUBjIaOf/VcYhNwi/g0HIWezu0GW5uq6rJeboRQPrxMNuxKVkBk1+l41IsysqOFa0DmYvB46f/n+Bs1cGhsyrCwavJiU0uask5Wb3grj/dFKrwtQvf2aw+QImttiKKbl+2wEhTYMZyDTFra0hfK7DU5/34QXNKcdRDXdzXnrzFnYcTKSBDplgUTgNyaQJKXDUNY1i4BUt6RSRaRaKIZ+6+JbdKjwJvdXdfhuCcKhQQ/j0iVuxjKlZxF3IrFjccjQdTUrT6vNwr7Dd8RxrwufmqdMuVt/+8okaMfH7425eTZ155w7nWacuNfVQsE9y4yg0NbKFXhPNJe6fT1SiXIShqrtDfoWACW6n981zVinrbXoIv5QcDSz5bAx00oaLD+AiFxbJzhEK980VAP5/VwXq7QEV1buaHiAtibdUhFEF7dHvk/eZDrsn7gyd2NZQlF69T0nmi9sx9yPAsZ0RjazkJXl4=
